binary_path = "samples/custom/sample.obf.c.out"

##################
# sample_obf_fib #
##################

[[virtual_machines]]
name = "sample_obf_fib"
bytecode_start = 0x405400
bytecode_end = 0x4054db
default_end = 0x401e37

[virtual_machines.locations]
vpc_offset = 0x160
vsp_offset = 0x158
locals_offset = 0x50
internal_offsets = [0x164]

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x401eff
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x402206
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe4
start = 0x40223c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9b
start = 0x401f76
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x401e9b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x4020e3
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa4
start = 0x401e4a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x402114
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc
start = 0x402176
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x69
start = 0x4021af
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7
start = 0x40206d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x60
start = 0x401fc0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x401f59
end = 0x4022a6
ret = true
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf3
start = 0x402025
detect_operands = true

[[virtual_machines.functions]]
name = "printf"
address = 0x401040
argument_count = 3

###################
# sample_obf_xtea #
###################

[[virtual_machines]]
name = "sample_obf_xtea"
bytecode_start = 0x405120
bytecode_end = 0x4053f7
default_end = 0x401573
functions = []

[virtual_machines.locations]
vpc_offset = 0x160
vsp_offset = 0x158
locals_offset = 0x50
internal_offsets = [0x168, 0x170, 0x178]

[[virtual_machines.handlers]]
opcode = 0x2f
start = 0x4018d8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xba
start = 0x401c79
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x8e
start = 0x401b06
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xed
start = 0x40193d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x97
start = 0x401aad
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb7
start = 0x40167d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x99
start = 0x401bcc
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2c
start = 0x40181b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xef
start = 0x401cad
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc4
start = 0x401873
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x35
start = 0x401633
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa
start = 0x40177b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb9
start = 0x401daf
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x401b37
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb0
start = 0x401bff
end = 0x401e00
ret = true
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xde
start = 0x401723
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x51
start = 0x401b70
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa0
start = 0x4019f8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x23
start = 0x401a50
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc6
start = 0x401c1c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xab
start = 0x401996
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x78
start = 0x401586
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6d
start = 0x4018a7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb3
start = 0x4017af
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xbf
start = 0x4016d9
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x91
start = 0x401909
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x5e
start = 0x4015db
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2e
start = 0x401d0a
detect_operands = true

#######################
# sample_obf_interact #
#######################

[[virtual_machines]]
name = "sample_obf_interact"
bytecode_start = 0x405040
bytecode_end = 0x405104
default_end = 0x401180

[virtual_machines.locations]
vpc_offset = 0x170
vsp_offset = 0x168
locals_offset = 0x60
internal_offsets = []

[[virtual_machines.handlers]]
opcode = 0x4
start = 0x401292
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x73
start = 0x4011b4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x4d
start = 0x401420
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x72
start = 0x4012c7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9c
start = 0x401482
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf7
start = 0x401193
end = 0x401535
ret = true
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x5e
start = 0x4013bb
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x87
start = 0x4014b4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x22
start = 0x401502
detect_operands = true

[[virtual_machines.functions]]
name = "__isoc99_scanf"
address = 0x401050
argument_count = 2

[[virtual_machines.functions]]
name = "puts"
address = 0x401030
argument_count = 1

[[virtual_machines.functions]]
name = "printf"
address = 0x401040
argument_count = 1
