binary_path = "samples/elfhash.obf.c.out"

#######################
# elfhash_obf_ELFHash #
#######################

[[virtual_machines]]
name = "elfhash_obf_ELFHash"
bytecode_start = 0x404040
bytecode_end = 0x404152
default_end = f0x40117d
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0xf9
start = 0x401830
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xad
start = 0x401217
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc
start = 0x4017ce
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb2
start = 0x401335
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x401190
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcc
start = 0x401601
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9b
start = 0x4014b5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa1
start = 0x4019c7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3
start = 0x4012c9
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe4
start = 0x401659
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x69
start = 0x401862
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xdf
start = 0x40190f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x24
start = 0x401531
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x34
start = 0x4011e4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb9
start = 0x401270
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x401561
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa4
start = 0x4016b2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x60
start = 0x401389
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7
start = 0x4013e1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x10
start = 0x4018bb
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x26
start = 0x4016e6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1c
start = 0x401969
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x40168c
end = 0x4019f4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6d
start = 0x4014ff
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf1
start = 0x4015a9
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x40173e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x401795
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x401435
detect_operands = true
