binary_path = "samples/fnvhash.obf.c.out"

#######################
# fnvhash_obf_FNVHash #
#######################

[[virtual_machines]]
name = "fnvhash_obf_FNVHash"
bytecode_start = 0x404040
bytecode_end = 0x4040f5
default_end = 0x40117d
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0x10
start = 0x401400
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x4011c0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9b
start = 0x401433
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb2
start = 0x40164c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf9
start = 0x40174e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3
start = 0x4016f9
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x24
start = 0x401784
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x60
start = 0x4015f4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa4
start = 0x4014fd
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x40159d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x4013da
end = 0x4017d8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcc
start = 0x401217
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x40124a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe4
start = 0x401190
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x69
start = 0x401348
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1c
start = 0x401531
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x40147d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x4013a1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7
start = 0x401292
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xad
start = 0x4016a0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc
start = 0x4012e6
detect_operands = true
