binary_path = "samples/pjwhash.obf.c.out"

#######################
# pjwhash_obf_PJWHash #
#######################

[[virtual_machines]]
name = "pjwhash_obf_PJWHash"
bytecode_start = 0x404040
bytecode_end = 0x404197
default_end = 0x40117d
functions = []

[virtual_machines.locations]
vpc_offset = 0x140
vsp_offset = 0x138
locals_offset = 0x30
internal_offsets = [0x148, 0x14c]

[[virtual_machines.handlers]]
opcode = 0x24
start = 0x401462
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc
start = 0x401779
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x4018a1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb9
start = 0x4017db
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x4011c1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x401623
end = 0x4019e0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xad
start = 0x4012cf
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcc
start = 0x4011f7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3
start = 0x401835
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe4
start = 0x401511
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x4014ba
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7
start = 0x401576
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x26
start = 0x4016f1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x69
start = 0x401328
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf9
start = 0x401544
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb2
start = 0x4013b4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa1
start = 0x401724
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x40124f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf1
start = 0x40169d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1c
start = 0x401408
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6d
start = 0x401381
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x10
start = 0x401649
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9b
start = 0x40199c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x401941
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x34
start = 0x4015ca
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa4
start = 0x401190
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x60
start = 0x4018e9
detect_operands = true
