binary_path = "samples/rshash.obf.c.out"

#####################
# rshash_obf_RSHash #
#####################

[[virtual_machines]]
name = "rshash_obf_RSHash"
bytecode_start = 0x404040
bytecode_end = 0x404107
default_end = 0x40121a
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0x69
start = 0x401471
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcc
start = 0x40132e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7
start = 0x40176a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x40141a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9b
start = 0x401574
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x10
start = 0x4017be
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x4014ca
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x40139a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf9
start = 0x4017f5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x401361
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe4
start = 0x4016b7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x40122d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xad
start = 0x4015f2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x4016ea
end = 0x401821
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa4
start = 0x4015be
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc
start = 0x401512
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb2
start = 0x401281
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3
start = 0x40164b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x60
start = 0x4012d6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1c
start = 0x401710
detect_operands = true
