/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

union _1_fib_$node ;
struct _IO_FILE ;
enum _1_fib_$op ;
enum _1_interact_$op ;
union _1_interact_$node ;
enum _1_xtea_$op ;
union _1_xtea_$node ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
void xtea(long *v , long *k , long N ) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
enum _1_interact_$op {
    _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__store_void_star$right_STA_0$left_STA_1 = 157,
    _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__convert_void_star2void_star$left_STA_0$result_STA_0__store_void_star$right_STA_0$left_STA_1 = 178,
    _1_interact__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0 = 200,
    _1_interact__switch$expr_STA_0$min_LIT_0$default_LAB_1$max_LIT_2$jumpTab_LABLST_3 = 60,
    _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__convert_void_star2void_star$left_STA_0$result_STA_0__store_void_star$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0 = 121,
    _1_interact__returnVoid$ = 59,
    _1_interact__goto$label_LAB_0 = 156,
    _1_interact__call$func_LIT_0 = 255,
    _1_interact__local$result_STA_0$value_LIT_0__store_void_star$right_STA_0$left_STA_1 = 242
} ;
unsigned char _1_interact_$array[1][179]  = { {        _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__convert_void_star2void_star$left_STA_0$result_STA_0__store_void_star$right_STA_0$left_STA_1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_interact__call$func_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__convert_void_star2void_star$left_STA_0$result_STA_0__store_void_star$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)3, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_interact__local$result_STA_0$value_LIT_0__store_void_star$right_STA_0$left_STA_1, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_interact__call$func_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_interact__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_interact__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_interact__switch$expr_STA_0$min_LIT_0$default_LAB_1$max_LIT_2$jumpTab_LABLST_3, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)96,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)3,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)48,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)72,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__store_void_star$right_STA_0$left_STA_1,        (unsigned char)32,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)6,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_interact__call$func_LIT_0,        (unsigned char)3,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_interact__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_interact__goto$label_LAB_0, 
            (unsigned char)164,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__store_void_star$right_STA_0$left_STA_1,        (unsigned char)40,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)10,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_interact__call$func_LIT_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_interact__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_interact__goto$label_LAB_0, 
            (unsigned char)140,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__store_void_star$right_STA_0$left_STA_1,        (unsigned char)48,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)14,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_interact__call$func_LIT_0,        (unsigned char)5,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_interact__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_interact__goto$label_LAB_0, 
            (unsigned char)116,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__store_void_star$right_STA_0$left_STA_1,        (unsigned char)56,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)20,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_interact__call$func_LIT_0,        (unsigned char)6,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_interact__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_interact__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_interact__goto$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_interact__goto$label_LAB_0,        (unsigned char)82,        (unsigned char)255, 
            (unsigned char)255,        (unsigned char)255,        _1_interact__returnVoid$}};
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int raise(int sig ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
union _1_fib_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
enum _1_xtea_$op {
    _1_xtea__load_void_star$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0__convert_int2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 52,
    _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1 = 100,
    _1_xtea__load_void_star$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Shiftrt_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 132,
    _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__convert_unsigned_long2long$left_STA_0$result_STA_0 = 140,
    _1_xtea__returnVoid$ = 246,
    _1_xtea__Shiftlt_unsigned_long_int2unsigned_long$right_STA_0$result_STA_0$left_STA_1__constant_int$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Shiftrt_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 77,
    _1_xtea__branchIfTrue$expr_STA_0$label_LAB_0 = 70,
    _1_xtea__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1 = 243,
    _1_xtea__load_long$left_STA_0$result_STA_0__constant_long$result_STA_0$value_LIT_0__Gt_long_long2int$right_STA_0$result_STA_0$left_STA_1__branchIfTrue$expr_STA_0$label_LAB_0 = 64,
    _1_xtea__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__MinusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 148,
    _1_xtea__formal$result_STA_0$value_LIT_0 = 153,
    _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__MinusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 125,
    _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0 = 32,
    _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 166,
    _1_xtea__load_long$left_STA_0$result_STA_0__Neg_long2long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 194,
    _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0 = 167,
    _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1 = 152,
    _1_xtea__goto$label_LAB_0 = 251,
    _1_xtea__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 173,
    _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0 = 114,
    _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Ne_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1 = 242,
    _1_xtea__load_void_star$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__BAnd_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 56,
    _1_xtea__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 171,
    _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__BAnd_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__convert_unsigned_long2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 69,
    _1_xtea__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1 = 208,
    _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__store_long$left_STA_0$right_STA_1 = 36,
    _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Ne_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1__branchIfTrue$expr_STA_0$label_LAB_0 = 81,
    _1_xtea__convert_unsigned_long2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 2,
    _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__store_long$left_STA_0$right_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__convert_unsigned_long2long$left_STA_0$result_STA_0 = 14
} ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern int puts(char const   *__s ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
extern void exit(int status ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
extern void signal(int sig , void *func ) ;
char const   *_1_fib_$strings  =    "fib(%i)=%i\n\000";
typedef struct _IO_FILE FILE;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double ceil(double x ) ;
char const   *_1_interact_$strings  =    "> \000%d\000one\000two\000three\000bye\000";
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long clock(void) ;
extern long time(long *tloc ) ;
unsigned char _1_xtea_$array[1][561]  = { {        _1_xtea__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__load_void_star$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0__convert_int2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__formal$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__load_void_star$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0__convert_int2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)185, 
            (unsigned char)121,        (unsigned char)55,        (unsigned char)158,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)40, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__formal$result_STA_0$value_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__load_long$left_STA_0$result_STA_0__constant_long$result_STA_0$value_LIT_0__Gt_long_long2int$right_STA_0$result_STA_0$left_STA_1__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)17,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__goto$label_LAB_0,        (unsigned char)219, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0, 
            (unsigned char)40,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__formal$result_STA_0$value_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)48,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)56, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Ne_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1,        (unsigned char)48,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)56,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__goto$label_LAB_0, 
            (unsigned char)112,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)32,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__Shiftlt_unsigned_long_int2unsigned_long$right_STA_0$result_STA_0$left_STA_1__constant_int$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Shiftrt_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        (unsigned char)5,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_xtea__formal$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__load_void_star$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__BAnd_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        (unsigned char)56,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)3,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__convert_unsigned_long2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0,        (unsigned char)56, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)24,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        (unsigned char)40,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)56,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)56, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__Shiftlt_unsigned_long_int2unsigned_long$right_STA_0$result_STA_0$left_STA_1__constant_int$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Shiftrt_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        (unsigned char)5,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)24,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_xtea__formal$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__load_void_star$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Shiftrt_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            (unsigned char)11,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)56,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__BAnd_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__convert_unsigned_long2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        (unsigned char)3,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0,        (unsigned char)56,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        (unsigned char)32, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1, 
            (unsigned char)32,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__goto$label_LAB_0,        (unsigned char)83,        (unsigned char)255,        (unsigned char)255, 
            (unsigned char)255,        _1_xtea__goto$label_LAB_0,        (unsigned char)78,        (unsigned char)255, 
            (unsigned char)255,        (unsigned char)255,        _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0,        (unsigned char)40, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__formal$result_STA_0$value_LIT_0, 
            (unsigned char)2,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__load_long$left_STA_0$result_STA_0__Neg_long2long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_xtea__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)64,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Ne_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1__branchIfTrue$expr_STA_0$label_LAB_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)64,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)26,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__goto$label_LAB_0,        (unsigned char)162,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__Shiftlt_unsigned_long_int2unsigned_long$right_STA_0$result_STA_0$left_STA_1__constant_int$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Shiftrt_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            (unsigned char)5,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_xtea__formal$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__load_void_star$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Shiftrt_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        (unsigned char)11, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)64, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__BAnd_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__convert_unsigned_long2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1, 
            (unsigned char)3,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0,        (unsigned char)64,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__MinusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)32, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__MinusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            (unsigned char)40,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)64,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)64,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__Shiftlt_unsigned_long_int2unsigned_long$right_STA_0$result_STA_0$left_STA_1__constant_int$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Shiftrt_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        (unsigned char)5, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)32, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_xtea__formal$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__load_void_star$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__BAnd_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        (unsigned char)64,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)3,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__convert_unsigned_long2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0, 
            (unsigned char)64,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__MinusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        (unsigned char)24,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1,        (unsigned char)24,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__goto$label_LAB_0,        (unsigned char)80, 
            (unsigned char)255,        (unsigned char)255,        (unsigned char)255,        _1_xtea__goto$label_LAB_0, 
            (unsigned char)75,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__convert_unsigned_long2long$left_STA_0$result_STA_0,        (unsigned char)24,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__load_void_star$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0__convert_int2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__store_long$left_STA_0$right_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__convert_unsigned_long2long$left_STA_0$result_STA_0, 
            (unsigned char)32,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_xtea__load_void_star$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0__convert_int2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__store_long$left_STA_0$right_STA_1,        _1_xtea__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_xtea__returnVoid$}};
extern int read(int filedes ,
                void *buf , unsigned int nbyte ) ;
extern int rand() ;
enum _1_fib_$op {
    _1_fib__goto$label_LAB_0 = 126,
    _1_fib__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0 = 69,
    _1_fib__formal$result_STA_0$value_LIT_0 = 183,
    _1_fib__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0 = 103,
    _1_fib__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1__store_int$right_STA_0$left_STA_1 = 21,
    _1_fib__string$result_STA_0$value_LIT_0__convert_void_star2void_star$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__store_void_star$left_STA_0$right_STA_1__local$result_STA_0$value_LIT_0 = 205,
    _1_fib__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0 = 198,
    _1_fib__store_int$right_STA_0$left_STA_1 = 20,
    _1_fib__load_int$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1__branchIfTrue$expr_STA_0$label_LAB_0 = 150,
    _1_fib__local$result_STA_0$value_LIT_0__constant_int$result_STA_0$value_LIT_0__store_int$right_STA_0$left_STA_1 = 250,
    _1_fib__load_int$left_STA_0$result_STA_0__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0 = 65,
    _1_fib__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0 = 47,
    _1_fib__returnVoid$ = 249,
    _1_fib__call$func_LIT_0 = 178,
    _1_fib__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0 = 224
} ;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
extern void *malloc(unsigned int size ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
void interact(void) ;
char const   *_1_xtea_$strings  =    "";
extern int nanosleep(int *rqtp , int *rmtp ) ;
union _1_interact_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
extern int pthread_mutex_unlock(int *mutex ) ;
union _1_xtea_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int atoi(char const   *s ) ;
unsigned char _1_fib_$array[1][178]  = { {        _1_fib__local$result_STA_0$value_LIT_0__constant_int$result_STA_0$value_LIT_0__store_int$right_STA_0$left_STA_1,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0__constant_int$result_STA_0$value_LIT_0__store_int$right_STA_0$left_STA_1,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0__constant_int$result_STA_0$value_LIT_0__store_int$right_STA_0$left_STA_1,        (unsigned char)12, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0__constant_int$result_STA_0$value_LIT_0__store_int$right_STA_0$left_STA_1, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__load_int$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)18, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__goto$label_LAB_0,        (unsigned char)59,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)12,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1__store_int$right_STA_0$left_STA_1,        _1_fib__goto$label_LAB_0,        (unsigned char)186, 
            (unsigned char)255,        (unsigned char)255,        (unsigned char)255,        _1_fib__goto$label_LAB_0, 
            (unsigned char)181,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_fib__string$result_STA_0$value_LIT_0__convert_void_star2void_star$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__store_void_star$left_STA_0$right_STA_1__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)24,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)32,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__load_int$left_STA_0$result_STA_0__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0,        (unsigned char)36, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)12, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__store_int$right_STA_0$left_STA_1, 
            _1_fib__call$func_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0,        (unsigned char)40,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)44,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__load_int$left_STA_0$result_STA_0__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0,        (unsigned char)48, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)40, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__store_int$right_STA_0$left_STA_1, 
            _1_fib__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__returnVoid$}};
extern int fscanf(struct _IO_FILE *stream ,
                  char const   *format  , ...) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
void megaInit(void) ;
void fib(int n ) ;
void interact(void) 
{ 
  char _1_interact_$locals[64] ;
  union _1_interact_$node _1_interact_$stack[1][32] ;
  union _1_interact_$node *_1_interact_$sp[1] ;
  unsigned char *_1_interact_$pc[1] ;
  unsigned char _1_interact_$currentOp ;
  int control16 ;
  int min17 ;
  int max18 ;
  int default19 ;
  unsigned char *jumpTab20 ;

  {
  _1_interact_$sp[0] = _1_interact_$stack[0];
  _1_interact_$pc[0] = _1_interact_$array[0];
  while (1) {
    _1_interact_$currentOp = *(_1_interact_$pc[0]);
    if (_1_interact_$currentOp == _1_interact__call$func_LIT_0) {
      (_1_interact_$pc[0]) ++;
      switch (*((int *)_1_interact_$pc[0])) {
      case 6: 
      puts(*((char const   **)(_1_interact_$locals + 56)));
      break;
      case 3: 
      puts(*((char const   **)(_1_interact_$locals + 32)));
      break;
      case 4: 
      puts(*((char const   **)(_1_interact_$locals + 40)));
      break;
      case 1: 
      printf(*((char const   * __restrict  *)(_1_interact_$locals + 0)));
      break;
      case 2: 
      scanf(*((char const   * __restrict  *)(_1_interact_$locals + 8)), *((int **)(_1_interact_$locals + 16)));
      break;
      case 5: 
      puts(*((char const   **)(_1_interact_$locals + 48)));
      break;
      }
      _1_interact_$pc[0] += 4;
    } else
    if (_1_interact_$currentOp == _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__store_void_star$right_STA_0$left_STA_1) {
      (_1_interact_$pc[0]) ++;
      (_1_interact_$sp[0] + 1)->_void_star = (void *)(_1_interact_$locals + *((int *)_1_interact_$pc[0]));
      (_1_interact_$sp[0] + 2)->_void_star = (void *)(_1_interact_$strings + *((int *)(_1_interact_$pc[0] + 4)));
      *((void **)(_1_interact_$sp[0] + 1)->_void_star) = (_1_interact_$sp[0] + 2)->_void_star;
      _1_interact_$pc[0] += 8;
    } else
    if (_1_interact_$currentOp == _1_interact__returnVoid$) {
      (_1_interact_$pc[0]) ++;
      return;
    } else
    if (_1_interact_$currentOp == _1_interact__local$result_STA_0$value_LIT_0__store_void_star$right_STA_0$left_STA_1) {
      (_1_interact_$pc[0]) ++;
      (_1_interact_$sp[0] + 1)->_void_star = (void *)(_1_interact_$locals + *((int *)_1_interact_$pc[0]));
      *((void **)(_1_interact_$sp[0] + 0)->_void_star) = (_1_interact_$sp[0] + 1)->_void_star;
      (_1_interact_$sp[0]) --;
      _1_interact_$pc[0] += 4;
    } else
    if (_1_interact_$currentOp == _1_interact__goto$label_LAB_0) {
      (_1_interact_$pc[0]) ++;
      _1_interact_$pc[0] += *((int *)_1_interact_$pc[0]);
    } else
    if (_1_interact_$currentOp == _1_interact__switch$expr_STA_0$min_LIT_0$default_LAB_1$max_LIT_2$jumpTab_LABLST_3) {
      (_1_interact_$pc[0]) ++;
      control16 = (_1_interact_$sp[0] + 0)->_int;
      (_1_interact_$sp[0]) --;
      min17 = *((int *)_1_interact_$pc[0]);
      max18 = *((int *)(_1_interact_$pc[0] + 8));
      default19 = *((int *)(_1_interact_$pc[0] + 4));
      jumpTab20 = (unsigned char *)(_1_interact_$pc[0] + 12);
      if (control16 < min17) {
        _1_interact_$pc[0] += default19;
      } else
      if (control16 > max18) {
        _1_interact_$pc[0] += default19;
      } else {
        _1_interact_$pc[0] += *((int *)((char *)jumpTab20 + (control16 - min17) * 4));
      }
    } else
    if (_1_interact_$currentOp == _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__convert_void_star2void_star$left_STA_0$result_STA_0__store_void_star$right_STA_0$left_STA_1) {
      (_1_interact_$pc[0]) ++;
      (_1_interact_$sp[0] + 1)->_void_star = (void *)(_1_interact_$locals + *((int *)_1_interact_$pc[0]));
      (_1_interact_$sp[0] + 2)->_void_star = (void *)(_1_interact_$strings + *((int *)(_1_interact_$pc[0] + 4)));
      (_1_interact_$sp[0] + 2)->_void_star = (_1_interact_$sp[0] + 2)->_void_star;
      *((void **)(_1_interact_$sp[0] + 1)->_void_star) = (_1_interact_$sp[0] + 2)->_void_star;
      _1_interact_$pc[0] += 8;
    } else
    if (_1_interact_$currentOp == _1_interact__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0) {
      (_1_interact_$pc[0]) ++;
      (_1_interact_$sp[0] + 1)->_void_star = (void *)(_1_interact_$locals + *((int *)_1_interact_$pc[0]));
      (_1_interact_$sp[0] + 1)->_int = *((int *)(_1_interact_$sp[0] + 1)->_void_star);
      (_1_interact_$sp[0]) ++;
      _1_interact_$pc[0] += 4;
    } else
    if (_1_interact_$currentOp == _1_interact__local$result_STA_0$value_LIT_0__string$result_STA_0$value_LIT_0__convert_void_star2void_star$left_STA_0$result_STA_0__store_void_star$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0) {
      (_1_interact_$pc[0]) ++;
      (_1_interact_$sp[0] + 1)->_void_star = (void *)(_1_interact_$locals + *((int *)_1_interact_$pc[0]));
      (_1_interact_$sp[0] + 2)->_void_star = (void *)(_1_interact_$strings + *((int *)(_1_interact_$pc[0] + 4)));
      (_1_interact_$sp[0] + 2)->_void_star = (_1_interact_$sp[0] + 2)->_void_star;
      *((void **)(_1_interact_$sp[0] + 1)->_void_star) = (_1_interact_$sp[0] + 2)->_void_star;
      (_1_interact_$sp[0] + 1)->_void_star = (void *)(_1_interact_$locals + *((int *)(_1_interact_$pc[0] + 8)));
      (_1_interact_$sp[0]) ++;
      _1_interact_$pc[0] += 12;
    } else {

    }
  }
}
}
void megaInit(void) 
{ 


  {

}
}
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  return (0);
}
}
void fib(int n ) 
{ 
  char _1_fib_$locals[52] ;
  union _1_fib_$node _1_fib_$stack[1][32] ;
  union _1_fib_$node *_1_fib_$sp[1] ;
  unsigned char *_1_fib_$pc[1] ;
  unsigned char _1_fib_$currentOp ;

  {
  _1_fib_$sp[0] = _1_fib_$stack[0];
  _1_fib_$pc[0] = _1_fib_$array[0];
  while (1) {
    _1_fib_$currentOp = *(_1_fib_$pc[0]);
    if (_1_fib_$currentOp == _1_fib__formal$result_STA_0$value_LIT_0) {
      (_1_fib_$pc[0]) ++;
      switch (*((int *)_1_fib_$pc[0])) {
      case 0: 
      (_1_fib_$sp[0] + 1)->_void_star = (void *)(& n);
      break;
      }
      (_1_fib_$sp[0]) ++;
      _1_fib_$pc[0] += 4;
    } else
    if (_1_fib_$currentOp == _1_fib__returnVoid$) {
      (_1_fib_$pc[0]) ++;
      return;
    } else
    if (_1_fib_$currentOp == _1_fib__string$result_STA_0$value_LIT_0__convert_void_star2void_star$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__store_void_star$left_STA_0$right_STA_1__local$result_STA_0$value_LIT_0) {
      (_1_fib_$pc[0]) ++;
      (_1_fib_$sp[0] + 1)->_void_star = (void *)(_1_fib_$strings + *((int *)_1_fib_$pc[0]));
      (_1_fib_$sp[0] + 1)->_void_star = (_1_fib_$sp[0] + 1)->_void_star;
      (_1_fib_$sp[0] + 2)->_void_star = (void *)(_1_fib_$locals + *((int *)(_1_fib_$pc[0] + 4)));
      *((void **)(_1_fib_$sp[0] + 2)->_void_star) = (_1_fib_$sp[0] + 1)->_void_star;
      (_1_fib_$sp[0] + 1)->_void_star = (void *)(_1_fib_$locals + *((int *)(_1_fib_$pc[0] + 8)));
      (_1_fib_$sp[0]) ++;
      _1_fib_$pc[0] += 12;
    } else
    if (_1_fib_$currentOp == _1_fib__load_int$left_STA_0$result_STA_0__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0) {
      (_1_fib_$pc[0]) ++;
      (_1_fib_$sp[0] + 0)->_int = *((int *)(_1_fib_$sp[0] + 0)->_void_star);
      *((int *)(_1_fib_$sp[0] + -1)->_void_star) = (_1_fib_$sp[0] + 0)->_int;
      (_1_fib_$sp[0] + -1)->_void_star = (void *)(_1_fib_$locals + *((int *)_1_fib_$pc[0]));
      (_1_fib_$sp[0] + 0)->_void_star = (void *)(_1_fib_$locals + *((int *)(_1_fib_$pc[0] + 4)));
      (_1_fib_$sp[0] + 0)->_int = *((int *)(_1_fib_$sp[0] + 0)->_void_star);
      _1_fib_$pc[0] += 8;
    } else
    if (_1_fib_$currentOp == _1_fib__goto$label_LAB_0) {
      (_1_fib_$pc[0]) ++;
      _1_fib_$pc[0] += *((int *)_1_fib_$pc[0]);
    } else
    if (_1_fib_$currentOp == _1_fib__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0) {
      (_1_fib_$pc[0]) ++;
      (_1_fib_$sp[0] + 1)->_void_star = (void *)(_1_fib_$locals + *((int *)_1_fib_$pc[0]));
      (_1_fib_$sp[0] + 2)->_void_star = (void *)(_1_fib_$locals + *((int *)(_1_fib_$pc[0] + 4)));
      _1_fib_$sp[0] += 2;
      _1_fib_$pc[0] += 8;
    } else
    if (_1_fib_$currentOp == _1_fib__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0) {
      (_1_fib_$pc[0]) ++;
      *((int *)(_1_fib_$sp[0] + -1)->_void_star) = (_1_fib_$sp[0] + 0)->_int;
      (_1_fib_$sp[0] + -1)->_void_star = (void *)(_1_fib_$locals + *((int *)_1_fib_$pc[0]));
      (_1_fib_$sp[0] + 0)->_void_star = (void *)(_1_fib_$locals + *((int *)(_1_fib_$pc[0] + 4)));
      (_1_fib_$sp[0] + 0)->_int = *((int *)(_1_fib_$sp[0] + 0)->_void_star);
      _1_fib_$pc[0] += 8;
    } else
    if (_1_fib_$currentOp == _1_fib__load_int$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1__branchIfTrue$expr_STA_0$label_LAB_0) {
      (_1_fib_$pc[0]) ++;
      (_1_fib_$sp[0] + 0)->_int = *((int *)(_1_fib_$sp[0] + 0)->_void_star);
      (_1_fib_$sp[0] + 1)->_void_star = (void *)(_1_fib_$locals + *((int *)_1_fib_$pc[0]));
      (_1_fib_$sp[0] + 1)->_int = *((int *)(_1_fib_$sp[0] + 1)->_void_star);
      (_1_fib_$sp[0] + 0)->_int = (_1_fib_$sp[0] + 1)->_int < (_1_fib_$sp[0] + 0)->_int;
      if ((_1_fib_$sp[0] + 0)->_int) {
        _1_fib_$pc[0] += *((int *)(_1_fib_$pc[0] + 4));
      } else {
        _1_fib_$pc[0] += 8;
      }
      (_1_fib_$sp[0]) --;
    } else
    if (_1_fib_$currentOp == _1_fib__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0) {
      (_1_fib_$pc[0]) ++;
      (_1_fib_$sp[0] + -1)->_int = (_1_fib_$sp[0] + -1)->_int + (_1_fib_$sp[0] + 0)->_int;
      *((int *)(_1_fib_$sp[0] + -2)->_void_star) = (_1_fib_$sp[0] + -1)->_int;
      (_1_fib_$sp[0] + -2)->_void_star = (void *)(_1_fib_$locals + *((int *)_1_fib_$pc[0]));
      (_1_fib_$sp[0] + -1)->_void_star = (void *)(_1_fib_$locals + *((int *)(_1_fib_$pc[0] + 4)));
      (_1_fib_$sp[0] + -1)->_int = *((int *)(_1_fib_$sp[0] + -1)->_void_star);
      (_1_fib_$sp[0]) --;
      _1_fib_$pc[0] += 8;
    } else
    if (_1_fib_$currentOp == _1_fib__call$func_LIT_0) {
      (_1_fib_$pc[0]) ++;
      switch (*((int *)_1_fib_$pc[0])) {
      case 1: 
      *((int *)(_1_fib_$locals + 44)) = printf(*((char const   * __restrict  *)(_1_fib_$locals + 24)),
                                               *((int *)(_1_fib_$locals + 32)), *((int *)(_1_fib_$locals + 36)));
      break;
      }
      _1_fib_$pc[0] += 4;
    } else
    if (_1_fib_$currentOp == _1_fib__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0) {
      (_1_fib_$pc[0]) ++;
      (_1_fib_$sp[0] + 1)->_void_star = (void *)(_1_fib_$locals + *((int *)_1_fib_$pc[0]));
      (_1_fib_$sp[0] + 2)->_void_star = (void *)(_1_fib_$locals + *((int *)(_1_fib_$pc[0] + 4)));
      (_1_fib_$sp[0] + 2)->_int = *((int *)(_1_fib_$sp[0] + 2)->_void_star);
      (_1_fib_$sp[0] + 3)->_void_star = (void *)(_1_fib_$locals + *((int *)(_1_fib_$pc[0] + 8)));
      (_1_fib_$sp[0] + 3)->_int = *((int *)(_1_fib_$sp[0] + 3)->_void_star);
      _1_fib_$sp[0] += 3;
      _1_fib_$pc[0] += 12;
    } else
    if (_1_fib_$currentOp == _1_fib__store_int$right_STA_0$left_STA_1) {
      (_1_fib_$pc[0]) ++;
      *((int *)(_1_fib_$sp[0] + -1)->_void_star) = (_1_fib_$sp[0] + 0)->_int;
      _1_fib_$sp[0] += -2;
    } else
    if (_1_fib_$currentOp == _1_fib__local$result_STA_0$value_LIT_0__constant_int$result_STA_0$value_LIT_0__store_int$right_STA_0$left_STA_1) {
      (_1_fib_$pc[0]) ++;
      (_1_fib_$sp[0] + 1)->_void_star = (void *)(_1_fib_$locals + *((int *)_1_fib_$pc[0]));
      (_1_fib_$sp[0] + 2)->_int = *((int *)(_1_fib_$pc[0] + 4));
      *((int *)(_1_fib_$sp[0] + 1)->_void_star) = (_1_fib_$sp[0] + 2)->_int;
      _1_fib_$pc[0] += 8;
    } else
    if (_1_fib_$currentOp == _1_fib__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1__store_int$right_STA_0$left_STA_1) {
      (_1_fib_$pc[0]) ++;
      (_1_fib_$sp[0] + -1)->_int = (_1_fib_$sp[0] + -1)->_int + (_1_fib_$sp[0] + 0)->_int;
      *((int *)(_1_fib_$sp[0] + -2)->_void_star) = (_1_fib_$sp[0] + -1)->_int;
      _1_fib_$sp[0] += -3;
    } else
    if (_1_fib_$currentOp == _1_fib__store_int$right_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_int$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0) {
      (_1_fib_$pc[0]) ++;
      *((int *)(_1_fib_$sp[0] + -1)->_void_star) = (_1_fib_$sp[0] + 0)->_int;
      (_1_fib_$sp[0] + -1)->_void_star = (void *)(_1_fib_$locals + *((int *)_1_fib_$pc[0]));
      (_1_fib_$sp[0] + 0)->_void_star = (void *)(_1_fib_$locals + *((int *)(_1_fib_$pc[0] + 4)));
      (_1_fib_$sp[0] + 0)->_int = *((int *)(_1_fib_$sp[0] + 0)->_void_star);
      (_1_fib_$sp[0] + 1)->_int = *((int *)(_1_fib_$pc[0] + 8));
      (_1_fib_$sp[0]) ++;
      _1_fib_$pc[0] += 12;
    } else {

    }
  }
}
}
void xtea(long *v , long *k , long N ) 
{ 
  char _1_xtea_$locals[72] ;
  union _1_xtea_$node _1_xtea_$stack[1][32] ;
  union _1_xtea_$node *_1_xtea_$sp[1] ;
  unsigned char *_1_xtea_$pc[1] ;
  unsigned char _1_xtea_$currentOp ;

  {
  _1_xtea_$sp[0] = _1_xtea_$stack[0];
  _1_xtea_$pc[0] = _1_xtea_$array[0];
  while (1) {
    _1_xtea_$currentOp = *(_1_xtea_$pc[0]);
    if (_1_xtea_$currentOp == _1_xtea__load_void_star$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0__convert_int2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 0)->_void_star = *((void **)(_1_xtea_$sp[0] + 0)->_void_star);
      (_1_xtea_$sp[0] + 1)->_int = *((int *)_1_xtea_$pc[0]);
      (_1_xtea_$sp[0] + 1)->_unsigned_long = (unsigned long )(_1_xtea_$sp[0] + 1)->_int;
      (_1_xtea_$sp[0] + 2)->_unsigned_long = *((unsigned long *)(_1_xtea_$pc[0] + 4));
      (_1_xtea_$sp[0] + 1)->_unsigned_long = (_1_xtea_$sp[0] + 1)->_unsigned_long * (_1_xtea_$sp[0] + 2)->_unsigned_long;
      (_1_xtea_$sp[0]) ++;
      _1_xtea_$pc[0] += 12;
    } else
    if (_1_xtea_$currentOp == _1_xtea__load_long$left_STA_0$result_STA_0__Neg_long2long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 0)->_long = *((long *)(_1_xtea_$sp[0] + 0)->_void_star);
      (_1_xtea_$sp[0] + 0)->_long = - (_1_xtea_$sp[0] + 0)->_long;
      (_1_xtea_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_xtea_$sp[0] + 0)->_long;
      (_1_xtea_$sp[0] + -1)->_unsigned_long = (_1_xtea_$sp[0] + -1)->_unsigned_long * (_1_xtea_$sp[0] + 0)->_unsigned_long;
      (_1_xtea_$sp[0]) --;
    } else
    if (_1_xtea_$currentOp == _1_xtea__load_void_star$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Shiftrt_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 0)->_void_star = *((void **)(_1_xtea_$sp[0] + 0)->_void_star);
      (_1_xtea_$sp[0] + 1)->_int = *((int *)_1_xtea_$pc[0]);
      (_1_xtea_$sp[0] + 2)->_void_star = (void *)(_1_xtea_$locals + *((int *)(_1_xtea_$pc[0] + 4)));
      (_1_xtea_$sp[0] + 2)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 2)->_void_star);
      (_1_xtea_$sp[0] + 1)->_unsigned_long = (_1_xtea_$sp[0] + 2)->_unsigned_long >> (_1_xtea_$sp[0] + 1)->_int;
      (_1_xtea_$sp[0]) ++;
      _1_xtea_$pc[0] += 8;
    } else
    if (_1_xtea_$currentOp == _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__convert_unsigned_long2long$left_STA_0$result_STA_0) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 1)->_void_star);
      (_1_xtea_$sp[0] + 1)->_long = (long )(_1_xtea_$sp[0] + 1)->_unsigned_long;
      (_1_xtea_$sp[0]) ++;
      _1_xtea_$pc[0] += 4;
    } else
    if (_1_xtea_$currentOp == _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Ne_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1__branchIfTrue$expr_STA_0$label_LAB_0) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_xtea_$pc[0]);
      (_1_xtea_$sp[0] + 2)->_void_star = (void *)(_1_xtea_$locals + *((int *)(_1_xtea_$pc[0] + 8)));
      (_1_xtea_$sp[0] + 2)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 2)->_void_star);
      (_1_xtea_$sp[0] + 1)->_int = (_1_xtea_$sp[0] + 2)->_unsigned_long != (_1_xtea_$sp[0] + 1)->_unsigned_long;
      if ((_1_xtea_$sp[0] + 1)->_int) {
        _1_xtea_$pc[0] += *((int *)(_1_xtea_$pc[0] + 12));
      } else {
        _1_xtea_$pc[0] += 16;
      }
    } else
    if (_1_xtea_$currentOp == _1_xtea__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + -1)->_unsigned_long = (_1_xtea_$sp[0] + -1)->_unsigned_long ^ (_1_xtea_$sp[0] + 0)->_unsigned_long;
      (_1_xtea_$sp[0] + -2)->_unsigned_long = (_1_xtea_$sp[0] + -1)->_unsigned_long + (_1_xtea_$sp[0] + -2)->_unsigned_long;
      _1_xtea_$sp[0] += -2;
    } else
    if (_1_xtea_$currentOp == _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__MinusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 1)->_void_star);
      (_1_xtea_$sp[0] + 2)->_void_star = (void *)(_1_xtea_$locals + *((int *)(_1_xtea_$pc[0] + 4)));
      (_1_xtea_$sp[0] + 2)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 2)->_void_star);
      (_1_xtea_$sp[0] + 1)->_unsigned_long = (_1_xtea_$sp[0] + 2)->_unsigned_long - (_1_xtea_$sp[0] + 1)->_unsigned_long;
      (_1_xtea_$sp[0]) ++;
      _1_xtea_$pc[0] += 8;
    } else
    if (_1_xtea_$currentOp == _1_xtea__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 0)->_long = *((long *)(_1_xtea_$sp[0] + 0)->_void_star);
      (_1_xtea_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_xtea_$sp[0] + 0)->_long;
      (_1_xtea_$sp[0] + -1)->_unsigned_long = (_1_xtea_$sp[0] + -1)->_unsigned_long * (_1_xtea_$sp[0] + 0)->_unsigned_long;
      (_1_xtea_$sp[0] + 0)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      *((unsigned long *)(_1_xtea_$sp[0] + 0)->_void_star) = (_1_xtea_$sp[0] + -1)->_unsigned_long;
      _1_xtea_$sp[0] += -2;
      _1_xtea_$pc[0] += 4;
    } else
    if (_1_xtea_$currentOp == _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + -1)->_void_star = (_1_xtea_$sp[0] + -1)->_void_star + (_1_xtea_$sp[0] + 0)->_unsigned_long;
      (_1_xtea_$sp[0] + -1)->_long = *((long *)(_1_xtea_$sp[0] + -1)->_void_star);
      (_1_xtea_$sp[0] + -1)->_unsigned_long = (unsigned long )(_1_xtea_$sp[0] + -1)->_long;
      (_1_xtea_$sp[0] + 0)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + 0)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 0)->_void_star);
      _1_xtea_$pc[0] += 4;
    } else
    if (_1_xtea_$currentOp == _1_xtea__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__MinusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + -1)->_unsigned_long = (_1_xtea_$sp[0] + 0)->_unsigned_long + (_1_xtea_$sp[0] + -1)->_unsigned_long;
      (_1_xtea_$sp[0] + -2)->_unsigned_long = (_1_xtea_$sp[0] + -2)->_unsigned_long ^ (_1_xtea_$sp[0] + -1)->_unsigned_long;
      (_1_xtea_$sp[0] + -1)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + -1)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + -1)->_void_star);
      (_1_xtea_$sp[0] + -2)->_unsigned_long = (_1_xtea_$sp[0] + -1)->_unsigned_long - (_1_xtea_$sp[0] + -2)->_unsigned_long;
      _1_xtea_$sp[0] += -2;
      _1_xtea_$pc[0] += 4;
    } else
    if (_1_xtea_$currentOp == _1_xtea__goto$label_LAB_0) {
      (_1_xtea_$pc[0]) ++;
      _1_xtea_$pc[0] += *((int *)_1_xtea_$pc[0]);
    } else
    if (_1_xtea_$currentOp == _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__store_long$left_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + -1)->_void_star = (_1_xtea_$sp[0] + -1)->_void_star + (_1_xtea_$sp[0] + 0)->_unsigned_long;
      *((long *)(_1_xtea_$sp[0] + -1)->_void_star) = (_1_xtea_$sp[0] + -2)->_long;
      _1_xtea_$sp[0] += -3;
    } else
    if (_1_xtea_$currentOp == _1_xtea__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1__BXor_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + -1)->_unsigned_long = (_1_xtea_$sp[0] + 0)->_unsigned_long + (_1_xtea_$sp[0] + -1)->_unsigned_long;
      (_1_xtea_$sp[0] + -2)->_unsigned_long = (_1_xtea_$sp[0] + -2)->_unsigned_long ^ (_1_xtea_$sp[0] + -1)->_unsigned_long;
      (_1_xtea_$sp[0] + -1)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + -1)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + -1)->_void_star);
      (_1_xtea_$sp[0] + -2)->_unsigned_long = (_1_xtea_$sp[0] + -1)->_unsigned_long + (_1_xtea_$sp[0] + -2)->_unsigned_long;
      _1_xtea_$sp[0] += -2;
      _1_xtea_$pc[0] += 4;
    } else
    if (_1_xtea_$currentOp == _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__store_long$left_STA_0$right_STA_1__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__convert_unsigned_long2long$left_STA_0$result_STA_0) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + -1)->_void_star = (_1_xtea_$sp[0] + -1)->_void_star + (_1_xtea_$sp[0] + 0)->_unsigned_long;
      *((long *)(_1_xtea_$sp[0] + -1)->_void_star) = (_1_xtea_$sp[0] + -2)->_long;
      (_1_xtea_$sp[0] + -2)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + -2)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + -2)->_void_star);
      (_1_xtea_$sp[0] + -2)->_long = (long )(_1_xtea_$sp[0] + -2)->_unsigned_long;
      _1_xtea_$sp[0] += -2;
      _1_xtea_$pc[0] += 4;
    } else
    if (_1_xtea_$currentOp == _1_xtea__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      *((unsigned long *)(_1_xtea_$sp[0] + 1)->_void_star) = (_1_xtea_$sp[0] + 0)->_unsigned_long;
      (_1_xtea_$sp[0]) --;
      _1_xtea_$pc[0] += 4;
    } else
    if (_1_xtea_$currentOp == _1_xtea__returnVoid$) {
      (_1_xtea_$pc[0]) ++;
      return;
    } else
    if (_1_xtea_$currentOp == _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 1)->_void_star);
      (_1_xtea_$sp[0]) ++;
      _1_xtea_$pc[0] += 4;
    } else
    if (_1_xtea_$currentOp == _1_xtea__load_long$left_STA_0$result_STA_0__constant_long$result_STA_0$value_LIT_0__Gt_long_long2int$right_STA_0$result_STA_0$left_STA_1__branchIfTrue$expr_STA_0$label_LAB_0) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 0)->_long = *((long *)(_1_xtea_$sp[0] + 0)->_void_star);
      (_1_xtea_$sp[0] + 1)->_long = *((long *)_1_xtea_$pc[0]);
      (_1_xtea_$sp[0] + 0)->_int = (_1_xtea_$sp[0] + 0)->_long > (_1_xtea_$sp[0] + 1)->_long;
      if ((_1_xtea_$sp[0] + 0)->_int) {
        _1_xtea_$pc[0] += *((int *)(_1_xtea_$pc[0] + 8));
      } else {
        _1_xtea_$pc[0] += 12;
      }
      (_1_xtea_$sp[0]) --;
    } else
    if (_1_xtea_$currentOp == _1_xtea__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1__load_long$left_STA_0$result_STA_0__convert_long2unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + -1)->_void_star = (_1_xtea_$sp[0] + -1)->_void_star + (_1_xtea_$sp[0] + 0)->_unsigned_long;
      (_1_xtea_$sp[0] + -1)->_long = *((long *)(_1_xtea_$sp[0] + -1)->_void_star);
      (_1_xtea_$sp[0] + -1)->_unsigned_long = (unsigned long )(_1_xtea_$sp[0] + -1)->_long;
      (_1_xtea_$sp[0] + 0)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      *((unsigned long *)(_1_xtea_$sp[0] + 0)->_void_star) = (_1_xtea_$sp[0] + -1)->_unsigned_long;
      _1_xtea_$sp[0] += -2;
      _1_xtea_$pc[0] += 4;
    } else
    if (_1_xtea_$currentOp == _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__store_unsigned_long$left_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_xtea_$pc[0]);
      (_1_xtea_$sp[0] + 2)->_void_star = (void *)(_1_xtea_$locals + *((int *)(_1_xtea_$pc[0] + 8)));
      *((unsigned long *)(_1_xtea_$sp[0] + 2)->_void_star) = (_1_xtea_$sp[0] + 1)->_unsigned_long;
      _1_xtea_$pc[0] += 12;
    } else
    if (_1_xtea_$currentOp == _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Ne_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 1)->_void_star);
      (_1_xtea_$sp[0] + 2)->_void_star = (void *)(_1_xtea_$locals + *((int *)(_1_xtea_$pc[0] + 4)));
      (_1_xtea_$sp[0] + 2)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 2)->_void_star);
      (_1_xtea_$sp[0] + 1)->_int = (_1_xtea_$sp[0] + 2)->_unsigned_long != (_1_xtea_$sp[0] + 1)->_unsigned_long;
      (_1_xtea_$sp[0]) ++;
      _1_xtea_$pc[0] += 8;
    } else
    if (_1_xtea_$currentOp == _1_xtea__Shiftlt_unsigned_long_int2unsigned_long$right_STA_0$result_STA_0$left_STA_1__constant_int$result_STA_0$value_LIT_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__Shiftrt_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + -1)->_unsigned_long = (_1_xtea_$sp[0] + -1)->_unsigned_long << (_1_xtea_$sp[0] + 0)->_int;
      (_1_xtea_$sp[0] + 0)->_int = *((int *)_1_xtea_$pc[0]);
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(_1_xtea_$locals + *((int *)(_1_xtea_$pc[0] + 4)));
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 1)->_void_star);
      (_1_xtea_$sp[0] + 0)->_unsigned_long = (_1_xtea_$sp[0] + 1)->_unsigned_long >> (_1_xtea_$sp[0] + 0)->_int;
      _1_xtea_$pc[0] += 8;
    } else
    if (_1_xtea_$currentOp == _1_xtea__branchIfTrue$expr_STA_0$label_LAB_0) {
      (_1_xtea_$pc[0]) ++;
      if ((_1_xtea_$sp[0] + 0)->_int) {
        _1_xtea_$pc[0] += *((int *)_1_xtea_$pc[0]);
      } else {
        _1_xtea_$pc[0] += 4;
      }
      (_1_xtea_$sp[0]) --;
    } else
    if (_1_xtea_$currentOp == _1_xtea__constant_unsigned_long$result_STA_0$value_LIT_0__BAnd_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1__convert_unsigned_long2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_xtea_$pc[0]);
      (_1_xtea_$sp[0] + 0)->_unsigned_long = (_1_xtea_$sp[0] + 0)->_unsigned_long & (_1_xtea_$sp[0] + 1)->_unsigned_long;
      (_1_xtea_$sp[0] + 0)->_unsigned_long = (_1_xtea_$sp[0] + 0)->_unsigned_long;
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)(_1_xtea_$pc[0] + 8));
      (_1_xtea_$sp[0] + 0)->_unsigned_long = (_1_xtea_$sp[0] + 0)->_unsigned_long * (_1_xtea_$sp[0] + 1)->_unsigned_long;
      _1_xtea_$pc[0] += 16;
    } else
    if (_1_xtea_$currentOp == _1_xtea__load_void_star$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__BAnd_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 0)->_void_star = *((void **)(_1_xtea_$sp[0] + 0)->_void_star);
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 1)->_void_star);
      (_1_xtea_$sp[0] + 2)->_unsigned_long = *((unsigned long *)(_1_xtea_$pc[0] + 4));
      (_1_xtea_$sp[0] + 1)->_unsigned_long = (_1_xtea_$sp[0] + 1)->_unsigned_long & (_1_xtea_$sp[0] + 2)->_unsigned_long;
      (_1_xtea_$sp[0]) ++;
      _1_xtea_$pc[0] += 12;
    } else
    if (_1_xtea_$currentOp == _1_xtea__convert_unsigned_long2unsigned_long$left_STA_0$result_STA_0__constant_unsigned_long$result_STA_0$value_LIT_0__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 0)->_unsigned_long = (_1_xtea_$sp[0] + 0)->_unsigned_long;
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_xtea_$pc[0]);
      (_1_xtea_$sp[0] + 0)->_unsigned_long = (_1_xtea_$sp[0] + 0)->_unsigned_long * (_1_xtea_$sp[0] + 1)->_unsigned_long;
      _1_xtea_$pc[0] += 8;
    } else
    if (_1_xtea_$currentOp == _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 1)->_void_star);
      (_1_xtea_$sp[0] + 2)->_void_star = (void *)(_1_xtea_$locals + *((int *)(_1_xtea_$pc[0] + 4)));
      (_1_xtea_$sp[0] + 2)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 2)->_void_star);
      (_1_xtea_$sp[0] + 1)->_unsigned_long = (_1_xtea_$sp[0] + 2)->_unsigned_long + (_1_xtea_$sp[0] + 1)->_unsigned_long;
      (_1_xtea_$sp[0]) ++;
      _1_xtea_$pc[0] += 8;
    } else
    if (_1_xtea_$currentOp == _1_xtea__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__local$result_STA_0$value_LIT_0__load_unsigned_long$left_STA_0$result_STA_0__constant_int$result_STA_0$value_LIT_0) {
      (_1_xtea_$pc[0]) ++;
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(_1_xtea_$locals + *((int *)_1_xtea_$pc[0]));
      (_1_xtea_$sp[0] + 1)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 1)->_void_star);
      (_1_xtea_$sp[0] + 2)->_void_star = (void *)(_1_xtea_$locals + *((int *)(_1_xtea_$pc[0] + 4)));
      (_1_xtea_$sp[0] + 2)->_unsigned_long = *((unsigned long *)(_1_xtea_$sp[0] + 2)->_void_star);
      (_1_xtea_$sp[0] + 3)->_int = *((int *)(_1_xtea_$pc[0] + 8));
      _1_xtea_$sp[0] += 3;
      _1_xtea_$pc[0] += 12;
    } else
    if (_1_xtea_$currentOp == _1_xtea__formal$result_STA_0$value_LIT_0) {
      (_1_xtea_$pc[0]) ++;
      switch (*((int *)_1_xtea_$pc[0])) {
      case 1: 
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(& k);
      break;
      case 2: 
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(& N);
      break;
      case 0: 
      (_1_xtea_$sp[0] + 1)->_void_star = (void *)(& v);
      break;
      }
      (_1_xtea_$sp[0]) ++;
      _1_xtea_$pc[0] += 4;
    } else {

    }
  }
}
}
