# Path relative to the project root directory
binary_path = "samples/sample1.out"

##########
# FIB VM #
##########

[[virtual_machines]]
name = "sample1-fib"

[virtual_machines.locations]
vpc_offset = 0x140
vsp_offset = 0x138
locals_offset = 0x30
internal_offsets = [0x144]

[[virtual_machines.handlers]]
opcode = 0xcf
start = 0x4018ac
end = 0x4018fb
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb5
start = 0x401903
end = 0x40195c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x17
start = 0x401967
end = 0x4019b3
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x68
start = 0x4019be
end = 0x4019ec
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc0
start = 0x4019f7
end = 0x401a4e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x55
start = 0x401a59
end = 0x401a98
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb9
start = 0x401aa3
end = 0x401aec
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2f
start = 0x401af7
end = 0x401b1d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x49
start = 0x401b28
end = 0x401b82
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x83
start = 0x401b8d
end = 0x401bee
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x79
start = 0x401bf9
end = 0x401c0b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x53
start = 0x401c16
end = 0x401c77
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xdb
start = 0x401c82
end = 0x401ca9
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x18
start = 0x401cb8
end = 0x401cf5
detect_operands = true

[[virtual_machines.functions]]
address = 0x401030
argument_count = 3

###########
# XTEA VM #
###########

[[virtual_machines]]
name = "sample1-xtea"
functions = []

[virtual_machines.locations]
vpc_offset = 0x140
vsp_offset = 0x138
locals_offset = 0x30
internal_offsets = [0x144, 0x150, 0x158]

[[virtual_machines.handlers]]
opcode = 0xee
start = 0x401171
end = 0x40119a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xfa
start = 0x4011a2
end = 0x4011ef
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb9
start = 0x4011fa
end = 0x401243
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7c
start = 0x40124e
end = 0x401260
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x8a
start = 0x40126b
end = 0x4012b9
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2f
start = 0x4012c4
end = 0x401313
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x97
start = 0x40131e
end = 0x401367
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf6
start = 0x401372
end = 0x40139a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xad
start = 0x4013a5
end = 0x4013f2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6f
start = 0x4013fd
end = 0x401421
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1a
start = 0x40142c
end = 0x401450
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x89
start = 0x40145b
end = 0x401498
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3d
start = 0x4014a3
end = 0x4014ec
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x4014f7
end = 0x40154e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xbb
start = 0x401559
end = 0x4015a5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1b
start = 0x4015b0
end = 0x4015d7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf0
start = 0x4015e2
end = 0x40162e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1f
start = 0x40163d
end = 0x4016d5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc1
start = 0x4016e0
end = 0x40172e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb1
start = 0x401739
end = 0x401760
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe2
start = 0x40176b
end = 0x4017b8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf4
start = 0x4017c3
end = 0x401824
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x0
start = 0x401833
end = 0x401861
detect_operands = true
