# Path relative to the project root directory
binary_path = "samples/samplea.out"

##########
# FIB VM #
##########

[[virtual_machines]]
name = "samplea-fib"
default_end = 0x401171

[virtual_machines.locations]
vpc_offset = 0x160
vsp_offset = 0x158
locals_offset = 0x50
internal_offsets = [0x164]

[[virtual_machines.handlers]]
opcode = 0xad
start = 0x401184
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa8
start = 0x4011e6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf2
start = 0x40123d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xaf
start = 0x40126f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x99
start = 0x4012db
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf9
start = 0x40132f
end = 0x401341
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x14
start = 0x40134c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7e
start = 0x401394
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf3
start = 0x4013cd
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x12
start = 0x401417
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb7
start = 0x401448
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3
start = 0x4014ac
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb2
start = 0x401506
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3e
start = 0x401580
detect_operands = true

[[virtual_machines.functions]]
address = 0x401040
argument_count = 3

###########
# XTEA VM #
###########

[[virtual_machines]]
name = "samplea-xtea"
default_end = 0x4019e7
functions = []

[virtual_machines.locations]
vpc_offset = 0x160
vsp_offset = 0x158
locals_offset = 0x50
internal_offsets = [0x168, 0x170, 0x178]

[[virtual_machines.handlers]]
opcode = 0x1b
start = 0x4019fa
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x52
start = 0x401a2b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x401a82
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x59
start = 0x401ada
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x81
start = 0x401b46
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x32
start = 0x401b9e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe4
start = 0x401bd7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x31
start = 0x401c30
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xdc
start = 0x401c8d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6b
start = 0x401d2e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf8
start = 0x401d5f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf2
start = 0x401d93
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x55
start = 0x401def
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x21
start = 0x401e23
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x90
start = 0x401e7b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd4
start = 0x401ed8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7a
start = 0x401f31
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x39
start = 0x401f7b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x5e
start = 0x401fdd
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd1
start = 0x402027
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2b
start = 0x402058
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe3
start = 0x40208b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xdf
start = 0x4020e3
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x8
start = 0x40213f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x70
start = 0x402173
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc3
start = 0x4021d0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xab
start = 0x402228
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xef
start = 0x40225d
end = 0x402270
detect_operands = true

###############
# INTERACT VM #
###############

[[virtual_machines]]
name = "samplea-interact"
default_end = 0x40160d

[virtual_machines.locations]
vpc_offset = 0x170
vsp_offset = 0x168
locals_offset = 0x60
internal_offsets = []

[[virtual_machines.handlers]]
opcode = 0x9e
start = 0x401624
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x401702
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1d
start = 0x401733
end = 0x401745
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd7
start = 0x401750
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1
start = 0x4017b5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6c
start = 0x401817
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa
start = 0x401850
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x77
start = 0x401886
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7c
start = 0x401968
detect_operands = true

# printf
[[virtual_machines.functions]]
address = 0x401040
argument_count = 1

# puts
[[virtual_machines.functions]]
address = 0x401030
argument_count = 1

# scanf
[[virtual_machines.functions]]
address = 0x401050
argument_count = 2
