# Path relative to the project root directory
binary_path = "samples/sampleb.out"

##########
# FIB VM #
##########

[[virtual_machines]]
name = "sampleb-fib"
default_end = 0x401746
bytecode_start = 0x406360
bytecode_end = 0x406412

[virtual_machines.locations]
vpc_offset = 0x160
vsp_offset = 0x158
locals_offset = 0x50
internal_offsets = [0x164]

[[virtual_machines.handlers]]
opcode = 0xb7
start = 0x401759
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf9
start = 0x4017ba
end = 0x4017cc
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcd
start = 0x4017db
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x41
start = 0x4018c9
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7e
start = 0x40197d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x67
start = 0x4019ba
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe0
start = 0x401a45
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x96
start = 0x401ae8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x45
start = 0x401bd6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb2
start = 0x401cbc
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2f
start = 0x401d36
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x14
start = 0x401e1c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xfa
start = 0x401e64
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x15
start = 0x401ee8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc6
start = 0x401f5d
detect_operands = true

[[virtual_machines.functions]]
name = "printf"
address = 0x401040
argument_count = 3

###########
# XTEA VM #
###########

[[virtual_machines]]
name = "sampleb-xtea"
default_end = 0x40205e
bytecode_start = 0x406120
bytecode_end = 0x406351
functions = []

[virtual_machines.locations]
vpc_offset = 0x160
vsp_offset = 0x158
locals_offset = 0x50
internal_offsets = [0x168, 0x170, 0x178]

[[virtual_machines.handlers]]
opcode = 0x34
start = 0x402075
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc2
start = 0x40214b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x84
start = 0x4021ea
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x8c
start = 0x4022d1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x51
start = 0x402372
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xad
start = 0x402465
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7d
start = 0x4024ee
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf3
start = 0x4025e4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa7
start = 0x4026b6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x94
start = 0x402781
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xfb
start = 0x402885
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x24
start = 0x4028be
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xab
start = 0x402939
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe
start = 0x402a41
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd0
start = 0x402b26
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf6
start = 0x402ba3
end = 0x402bb5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x72
start = 0x402bc0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x40
start = 0x402c45
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x64
start = 0x402d12
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x402df3
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf2
start = 0x402e82
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x4d
start = 0x402f7d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x46
start = 0x403058
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x45
start = 0x4030c8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x38
start = 0x40318b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2
start = 0x403269
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa6
start = 0x4032ee
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x20
start = 0x4033e4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x99
start = 0x4034c4
detect_operands = true

###############
# INTERACT VM #
###############

[[virtual_machines]]
name = "sampleb-interact"
default_end = 0x40116a
bytecode_start = 0x406040
bytecode_end = 0x4060f3

[virtual_machines.locations]
vpc_offset = 0x170
vsp_offset = 0x168
locals_offset = 0x60
internal_offsets = []

[[virtual_machines.handlers]]
opcode = 0xff
start = 0x401181
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9d
start = 0x401263
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3b
start = 0x4012fa
end = 0x40130c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf2
start = 0x401317
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9c
start = 0x401394
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3c
start = 0x4013d1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb2
start = 0x4014b3
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc8
start = 0x401566
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x79
start = 0x4015e9
detect_operands = true

[[virtual_machines.functions]]
name = "puts"
address = 0x401030
argument_count = 1

[[virtual_machines.functions]]
name = "printf"
address = 0x401040
argument_count = 1

[[virtual_machines.functions]]
name = "scanf"
address = 0x401050
argument_count = 3

