# Path relative to the project root directory
binary_path = "samples/sample2.out"

##########
# FIB VM #
##########

[[virtual_machines]]
name = "sample2-fib"

[virtual_machines.locations]
vpc_offset = 0x160
vsp_offset = 0x158
locals_offset = 0x50
internal_offsets = [0x164]

[[virtual_machines.handlers]]
opcode = 0x88
start = 0x401164
end = 0x401176
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf9
start = 0x401185
end = 0x40122e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe4
start = 0x40123d
end = 0x40131c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xfc
start = 0x40132b
end = 0x4013bf
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3
start = 0x4013ce
end = 0x401473
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7f
start = 0x40147e
end = 0x4014f2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc7
start = 0x401501
end = 0x40157d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x44
start = 0x401588
end = 0x4015b6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x67
start = 0x4015c1
end = 0x40161a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x38
start = 0x401629
end = 0x4016ba
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb9
start = 0x4016c5
end = 0x401730
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x54
start = 0x40173f
end = 0x4017e7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe2
start = 0x4017f2
end = 0x401862
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe7
start = 0x401871
end = 0x401936
detect_operands = true

[[virtual_machines.functions]]
address = 0x401030
argument_count = 3

###########
# XTEA VM #
###########

[[virtual_machines]]
name = "sample2-xtea"
functions = []

[virtual_machines.locations]
vpc_offset = 0x140
vsp_offset = 0x138
locals_offset = 0x30
internal_offsets = [0x144, 0x150, 0x158]

[[virtual_machines.handlers]]
opcode = 0xb7
start = 0x4019e6
end = 0x401aa1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x55
start = 0x401ab0
end = 0x401b79
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3b
start = 0x401b88
end = 0x401c4a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x59
start = 0x401c59
end = 0x401d08
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x5e
start = 0x401d17
end = 0x401de4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd4
start = 0x401df3
end = 0x401ec4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x76
start = 0x401ed3
end = 0x401fb2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xeb
start = 0x401fbd
end = 0x40202d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xae
start = 0x40203c
end = 0x402109
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x13
start = 0x402114
end = 0x40218b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa5
start = 0x40219a
end = 0x40225e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6a
start = 0x40226d
end = 0x40232e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x82
start = 0x40233d
end = 0x4023fe
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x28
start = 0x40240d
end = 0x4024d6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x5a
start = 0x4024e5
end = 0x4025cc
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf0
start = 0x4025db
end = 0x402673
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xfc
start = 0x402682
end = 0x402732
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2a
start = 0x402741
end = 0x4027f5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x91
start = 0x402800
end = 0x402812
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x402821
end = 0x4028a2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x51
start = 0x4028b1
end = 0x402970
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x8d
start = 0x40297b
end = 0x4029ef
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x4029fa
end = 0x402a28
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2f
start = 0x402a37
end = 0x402acf
detect_operands = true

