# Path relative to the project root directory
binary_path = "samples/sample1.out"

##########
# FIB VM #
##########

[[virtual_machines]]
name = "sample1-fib"

[virtual_machines.locations]
vpc_offset = 0x160
vsp_offset = 0x158
locals_offset = 0x50
internal_offsets = [0x164]

[[virtual_machines.handlers]]
opcode = 0x85
start = 0x4011ba
end = 0x401211
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2f
start = 0x401219
end = 0x40123f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x21
start = 0x40124a
end = 0x401293
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd6
start = 0x40129e
end = 0x4012f7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6f
start = 0x401302
end = 0x401314
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x25
start = 0x40131f
end = 0x40135e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc9
start = 0x401369
end = 0x401390
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe3
start = 0x40139b
end = 0x4013e7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6d
start = 0x4013f2
end = 0x40142f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf6
start = 0x40143a
end = 0x401494
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xac
start = 0x40149f
end = 0x4014ee
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7a
start = 0x4014f9
end = 0x401527
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf4
start = 0x401532
end = 0x40159d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb0
start = 0x4015ac
end = 0x40160d
detect_operands = true

[[virtual_machines.functions]]
address = 0x401030
argument_count = 3

###########
# XTEA VM #
###########

[[virtual_machines]]
name = "sample1-xtea"
functions = []

[virtual_machines.locations]
vpc_offset = 0x140
vsp_offset = 0x138
locals_offset = 0x30
internal_offsets = [0x144, 0x150, 0x158]

[[virtual_machines.handlers]]
opcode = 0x5f
start = 0x401663
end = 0x401675
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc0
start = 0x401680
end = 0x4016bd
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf8
start = 0x4016c5
end = 0x40170e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x70
start = 0x401719
end = 0x401765
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x29
start = 0x401770
end = 0x4017c7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x57
start = 0x4017d2
end = 0x4017f9
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3f
start = 0x401804
end = 0x40184d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe5
start = 0x401858
end = 0x401886
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x20
start = 0x401891
end = 0x4018de
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x64
start = 0x4018e9
end = 0x401932
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa0
start = 0x40193d
end = 0x40198a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x38
start = 0x401995
end = 0x4019e1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x33
start = 0x4019ec
end = 0x401a39
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x34
start = 0x401a44
end = 0x401aa5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xac
start = 0x401ab0
end = 0x401ad8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x44
start = 0x401ae3
end = 0x401b07
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb5
start = 0x401b16
end = 0x401bae
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb6
start = 0x401bb9
end = 0x401be2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9c
start = 0x401bed
end = 0x401c3b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf5
start = 0x401c46
end = 0x401c6d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9f
start = 0x401c78
end = 0x401c9c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x79
start = 0x401ca7
end = 0x401cf6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x81
start = 0x401d05
end = 0x401d53
detect_operands = true

