# Path relative to the project root directory
binary_path = "samples/sample2.out"

##########
# FIB VM #
##########

[[virtual_machines]]
name = "sample2-fib"

[virtual_machines.locations]
vpc_offset = 0x140
vsp_offset = 0x138
locals_offset = 0x30
internal_offsets = [0x144]

[[virtual_machines.handlers]]
opcode = 0x86
start = 0x401163
end = 0x4011d7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x45
start = 0x4011e6
end = 0x40128f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x96
start = 0x40129e
end = 0x401346
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb4
start = 0x401351
end = 0x4013b2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb6
start = 0x4013c1
end = 0x40143d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x77
start = 0x40144c
end = 0x4014e0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa2
start = 0x4014eb
end = 0x4014fd
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe7
start = 0x40150c
end = 0x40159d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x28
start = 0x4015ac
end = 0x40168b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x2
start = 0x401696
end = 0x401706
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd9
start = 0x401715
end = 0x4017da
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x51
start = 0x4017e5
end = 0x40183e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x18
start = 0x40184d
end = 0x4018f2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x401901
end = 0x40192f
detect_operands = true

[[virtual_machines.functions]]
address = 0x401030
argument_count = 3

###########
# XTEA VM #
###########

[[virtual_machines]]
name = "sample2-xtea"
functions = []

[virtual_machines.locations]
vpc_offset = 0x140
vsp_offset = 0x138
locals_offset = 0x30
internal_offsets = [0x144, 0x150, 0x158]

[[virtual_machines.handlers]]
opcode = 0xef
start = 0x4019db
end = 0x401ab6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf7
start = 0x401ac5
end = 0x401ba4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x34
start = 0x401bb3
end = 0x401c7a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x29
start = 0x401c89
end = 0x401d43
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xfb
start = 0x401d52
end = 0x401e02
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb8
start = 0x401e11
end = 0x401ebb
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6f
start = 0x401ec6
end = 0x401ef4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xbf
start = 0x401f03
end = 0x401fd2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x74
start = 0x401fe1
end = 0x4020b2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xda
start = 0x4020bd
end = 0x402131
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe8
start = 0x40213c
end = 0x402193
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9d
start = 0x4021a2
end = 0x402291
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x5f
start = 0x4022a0
end = 0x40236e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x71
start = 0x40237d
end = 0x40242b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1b
start = 0x402436
end = 0x4024ac
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb3
start = 0x4024bb
end = 0x402585
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd1
start = 0x402594
end = 0x40262c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x60
start = 0x40263b
end = 0x402705
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xdc
start = 0x402710
end = 0x402789
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x93
start = 0x402798
end = 0x402854
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xed
start = 0x40285f
end = 0x4028c5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf4
start = 0x4028d4
end = 0x4028e6
detect_operands = true
