binary_path = "samples/sdbmhash.sobf.c.out"

##########################
# sdbmhash_sobf_SDBMHash #
##########################

[[virtual_machines]]
name = "sdbmhash_sobf_SDBMHash"
bytecode_start = 0x404040
bytecode_end = 0x4040cf
default_end = f0x40117d
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0xe2
start = 0x4015ba
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6d
start = 0x401213
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x68
start = 0x40171a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd2
start = 0x4017d9
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x34
start = 0x40129e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb9
start = 0x401190
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x40134e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb0
start = 0x4014f1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x401696
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x8c
start = 0x40138b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x401670
end = 0x4018b1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x94
start = 0x401451
detect_operands = true
