binary_path = "samples/simple_hash/bphash.obf.c.out"

#####################
# bphash_obf_BPHash #
#####################

[[virtual_machines]]
name = "bphash_obf_BPHash"
bytecode_start = 0x404040
bytecode_end = 0x4040dd
default_end = 0x40121a
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0xb2
start = 0x401494
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xad
start = 0x401676
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x40145b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1c
start = 0x401395
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x4017b5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x40133e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcc
start = 0x401782
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf9
start = 0x4014e8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x401702
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x24
start = 0x401401
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3
start = 0x4016cf
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x60
start = 0x4012e6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc
start = 0x401284
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa4
start = 0x40122d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x10
start = 0x4015ca
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9b
start = 0x401834
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x69
start = 0x401571
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7
start = 0x401622
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x40125e
end = 0x401878
ret = true
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x40151a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe4
start = 0x4017fd
detect_operands = true
