binary_path = "samples/simple_hash/bphash.sobf.c.out"

######################
# bphash_sobf_BPHash #
######################

[[virtual_machines]]
name = "bphash_sobf_BPHash"
bytecode_start = 0x404040
bytecode_end = 0x4040c2
default_end = 0x40117d
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0x0
start = 0x4014d2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb9
start = 0x40158d
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x35
start = 0x4016ee
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x6d
start = 0x401354
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x401190
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x34
start = 0x4012a0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb0
start = 0x401636
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x4013db
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x4017d0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xdf
start = 0x4011d9
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x40160c
end = 0x40184a
ret = true
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xda
start = 0x401418
detect_operands = true
