binary_path = "samples/simple_hash/djbhash.obf.c.out"

#######################
# djbhash_obf_DJBHash #
#######################

[[virtual_machines]]
name = "djbhash_obf_DJBHash"
bytecode_start = 0x404040
bytecode_end = 0x4040e4
default_end = 0x40117d
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0xc
start = 0x401190
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x40130e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3
start = 0x40138b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7
start = 0x4015ae
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x60
start = 0x401556
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x4014a6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x401249
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb2
start = 0x4016fe
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf9
start = 0x40164c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcc
start = 0x401282
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9b
start = 0x401602
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xad
start = 0x4012b5
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x69
start = 0x4014fd
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x10
start = 0x40175a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1c
start = 0x4011ef
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x40142b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe4
start = 0x401473
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x401365
end = 0x401787
ret = true
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x40167e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa4
start = 0x4013f7
detect_operands = true
