binary_path = "samples/simple_hash/djbhash.sobf.c.out"

########################
# djbhash_sobf_DJBHash #
########################

[[virtual_machines]]
name = "djbhash_sobf_DJBHash"
bytecode_start = 0x404040
bytecode_end = 0x4040c6
default_end = 0x40117d
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0x26
start = 0x401364
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x35
start = 0x4016e1
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xea
start = 0x40179c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x401625
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7c
start = 0x40156f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xab
start = 0x40165e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb7
start = 0x401809
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x4018f8
end = 0x401913
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x34
start = 0x401194
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x4013eb
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x401523
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x0
start = 0x40146f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x4e
start = 0x401282
detect_operands = true
