binary_path = "samples/simple_hash/elfhash.sobf.c.out"

########################
# elfhash_sobf_ELFHash #
########################

[[virtual_machines]]
name = "elfhash_sobf_ELFHash"
bytecode_start = 0x404040
bytecode_end = 0x40411c
default_end = 0x40117d
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x4015ca
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7f
start = 0x4016d2
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x32
start = 0x4012de
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc1
start = 0x401902
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xbb
start = 0x4013ba
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x94
start = 0x4014e0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x4019e6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x68
start = 0x401afc
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xda
start = 0x401bec
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x401bc2
end = 0x401e2a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa3
start = 0x401194
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7c
start = 0x401616
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb7
start = 0x401253
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x4014a3
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x92
start = 0x40187f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd6
start = 0x401a6a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9c
start = 0x4017ae
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x78
start = 0x401d75
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x86
start = 0x401ca4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xbb
start = 0x4013ba
detect_operands = true
