binary_path = "samples/simple_hash/fnvhash.sobf.c.out"

########################
# fnvhash_sobf_FNVHash #
########################

[[virtual_machines]]
name = "fnvhash_sobf_FNVHash"
bytecode_start = 0x404040
bytecode_end = 0x4040d4
default_end = 0x40121a
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0x6d
start = 0x401529
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb9
start = 0x401695
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x66
start = 0x401718
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9e
start = 0x401320
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x34
start = 0x4017fa
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xda
start = 0x40146f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x4013b7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb7
start = 0x40192e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x4018aa
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x40166f
end = 0x4019c7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x8c
start = 0x4013f0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xdf
start = 0x401231
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x96
start = 0x4015b4
detect_operands = true
