binary_path = "samples/simple_hash/rshash.sobf.c.out"

######################
# rshash_sobf_RSHash #
######################

[[virtual_machines]]
name = "rshash_sobf_RSHash"
bytecode_start = 0x404040
bytecode_end = 0x4040e1
default_end = 0x401184
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x401484
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x4017b4
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe2
start = 0x4018b8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x26
start = 0x40119b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9e
start = 0x4013d0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x40144b
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xdf
start = 0x401226
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xd2
start = 0x40152e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x96
start = 0x401315
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x4e
start = 0x401610
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb0
start = 0x401800
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x401504
end = 0x401931
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x34
start = 0x4016ca
detect_operands = true
