binary_path = "samples/simple_hash/sdbmhash.obf.c.out"

#########################
# sdbmhash_obf_SDBMHash #
#########################

[[virtual_machines]]
name = "sdbmhash_obf_SDBMHash"
bytecode_start = 0x404040
bytecode_end = 0x4040f1
default_end = 0x40117d
functions = []

[virtual_machines.locations]
vpc_offset = 0x130
vsp_offset = 0x128
locals_offset = 0x20
internal_offsets = [0x138, 0x13c]

[[virtual_machines.handlers]]
opcode = 0xca
start = 0x40140a
end = 0x4017db
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x69
start = 0x40137e
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9b
start = 0x401463
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x24
start = 0x40167c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x60
start = 0x401624
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe9
start = 0x4017a8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x75
start = 0x4011c0
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x1c
start = 0x401561
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xb2
start = 0x4016d6
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xc
start = 0x40131c
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x98
start = 0x4015cd
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xad
start = 0x40126f
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x3
start = 0x401217
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xf9
start = 0x401772
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xe4
start = 0x401190
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x9a
start = 0x4014ad
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcb
start = 0x40172a
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xcc
start = 0x4013d7
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x7
start = 0x4012c8
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0x10
start = 0x401430
detect_operands = true

[[virtual_machines.handlers]]
opcode = 0xa4
start = 0x40152d
detect_operands = true
